GET http://localhost:3000/api/contents

###
POST http://localhost:3000/api/contents
Content-Type: application/json

{
  "content": "doing my homework"
}

###
DELETE http://localhost:3000/api/contents/

###
PATCH http://localhost:3000/api/contents/update/2
Content-Type: application/json

{
   "content": "playing game"
}